# Generated by Django 3.1.4 on 2020-12-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201208_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_default_news',
            field=models.CharField(choices=[('Article', 'Статья'), ('News', 'Новость')], default='News', max_length=7),
        ),
    ]
