# Generated by Django 3.1.4 on 2020-12-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201227_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_default_news',
            field=models.CharField(choices=[('Статья', 'Статья'), ('Новость', 'Новость')], default='Новость', max_length=7),
        ),
    ]
